name: Build APK S24FE

on: [push]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build APK
        run: |
          flet build apk --org com.sandros24fe.optimizer --product "Optimizer S24FE" --verbose
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Optimizer-S24FE
          path: build/apk/*.apk
